name: LateralThinkingPuzzle
options:
  bundleIdPrefix: com.kazuasato
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_TESTING_SEARCH_PATHS: YES

targets:
  LateralThinkingPuzzle:
    type: application
    platform: iOS
    sources:
      - path: LateralThinkingPuzzle
        excludes:
          - "Resources/**"
      - path: LateralThinkingPuzzle/Resources/Assets.xcassets
        buildPhase: resources
      - path: LateralThinkingPuzzle/Resources/Puzzles
        buildPhase: resources
        type: folder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 76359B69WG
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.kazuasato.LateralThinkingPuzzle
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: targeted
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: LateralQ
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

  LateralThinkingPuzzleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LateralThinkingPuzzleTests
    dependencies:
      - target: LateralThinkingPuzzle
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LateralThinkingPuzzle.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LateralThinkingPuzzle"

  LateralThinkingPuzzleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LateralThinkingPuzzleUITests
    dependencies:
      - target: LateralThinkingPuzzle
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
