name: LateralThinkingPuzzle
options:
  bundleIdPrefix: com.asatokazu
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_TESTING_SEARCH_PATHS: YES

targets:
  LateralThinkingPuzzle:
    type: application
    platform: iOS
    sources:
      - path: LateralThinkingPuzzle
        excludes:
          - "**/*.xcassets"
    resources:
      - path: LateralThinkingPuzzle/Resources
        buildPhase: resources
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.asatokazu.LateralThinkingPuzzle
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: targeted

  LateralThinkingPuzzleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LateralThinkingPuzzleTests
    dependencies:
      - target: LateralThinkingPuzzle
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LateralThinkingPuzzle.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LateralThinkingPuzzle"

  LateralThinkingPuzzleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LateralThinkingPuzzleUITests
    dependencies:
      - target: LateralThinkingPuzzle
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
